### PR TITLE
Translations to p.a.locale

### PR DESCRIPTION
**Pull request by staeff**

### CODE REVIEW

**Comment by vincentfretin** [comment]
You need to revert the pl_message changes. We need to keep using plonelocales domain here.

**Comment by vincentfretin** [comment]
maybe not, do the messagse already exists in plonelocales.po in plone.app.locales? If not, well I think this PR is ok.

**Comment by vincentfretin** [comment]
@staeff Yes, you definitely need to revert the pl_message changes.

**Comment by staeff** [comment]
@vincentfretin ok, I'll do that.

**Comment by mauritsvanrees** [comment]
Please remind me: can this be used on both Plone 5.0 and 5.1?

**Comment by vincentfretin** [comment]
I guess

**Comment by thet** [comment]
@mauritsvanrees yes, I'm pretty sure about that

**Comment by mauritsvanrees** [comment]
Thanks. I have released 2.1.0 for Plone 5.0 and 5.1.

**Pull request merged**
