### PR TITLE
Update plone-package-test.yml

### PR DESCRIPTION
**Pull request by gforcada**
Bump actions versions

### CODE REVIEW

**Comment by gforcada** [comment]
@ericof @petschki any idea what's wrong with the workflow jobs that are failing? 🤔 I see that it uses `plone/setup-plone`, I bumped it to the `2.0.0` release but still fails 😕

**Comment by petschki** [comment]
`--install-options` got removed afaik.

**Comment by petschki** [comment]
jobs are green now ... had nothing to do with `plone/setup-plone` but with the existing `mxdev` setup.

**Comment by gforcada** [comment]
Cool, thanks, the `pre-commit` errors will be fixed in #35

**Comment by petschki** [comment]
Note: I renamed the `sources.ini` to `mx.ini`... should be ingnored anyway by MANIFEST though ...

**Pull request merged**
